# Generated by Django 5.0.2 on 2024-03-09 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInformation',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=255)),
                ('accountNo', models.CharField(max_length=15)),
                ('bank', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isDeletedBy_bankInformation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AccountInformation',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookerFirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('bookerLastName', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('accessCode', models.CharField(blank=True, max_length=6, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointmentDate', models.DateTimeField(auto_now_add=True)),
                ('rescheduledDate', models.DateTimeField(blank=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy_appointment', to=settings.AUTH_USER_MODEL)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_appointment', to='grace_forte_app.booking')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paymentStatus', models.CharField(default='Pending', max_length=50)),
                ('paymentProof', models.FileField(blank=True, null=True, upload_to='payment_proof/')),
                ('proofBase', models.TextField()),
                ('sessionAmount', models.IntegerField(default=1)),
                ('totalExpectedAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('approvedDate', models.DateTimeField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='grace_forte_app.booking')),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BookingPayments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accessLink', models.CharField(blank=True, max_length=255, null=True)),
                ('imageBase', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy_course', to=settings.AUTH_USER_MODEL)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('middleName', models.CharField(blank=True, max_length=255, null=True)),
                ('homeAddress', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullTitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hierarchies',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHierarchy',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='grace_forte_app.employee')),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to='grace_forte_app.hierarchy')),
            ],
            options={
                'verbose_name_plural': 'EmployeeHierarchies',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy_planType', to=settings.AUTH_USER_MODEL)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PlanTypes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('imageBase', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('dateUpdated', models.DateTimeField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRendered',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('imageBase', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('priceType', models.CharField(blank=True, max_length=255, null=True)),
                ('isAvailable', models.BooleanField(default=True)),
                ('dateUpdated', models.DateTimeField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isDeletedBy', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceRendered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceRendered', to='grace_forte_app.servicerendered'),
        ),
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy_sessionPlan', to=settings.AUTH_USER_MODEL)),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planType', to='grace_forte_app.plantype')),
            ],
            options={
                'verbose_name_plural': 'SessionPlans',
            },
        ),
        migrations.CreateModel(
            name='TrainingPayment',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paymentStatus', models.CharField(default='Pending', max_length=50)),
                ('proofBase', models.TextField()),
                ('expectedAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('approvedDate', models.DateTimeField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_information', to='grace_forte_app.accountinformation')),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy_trainingPayment', to=settings.AUTH_USER_MODEL)),
                ('enrolledCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_training_payment', to='grace_forte_app.course')),
                ('isDeletedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_training_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TrainingPayments',
            },
        ),
    ]
