# Generated by Django 5.0.2 on 2024-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace_forte_app', '0002_accountinformation_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpayment',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
