# Generated by Django 5.0.2 on 2024-03-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace_forte_app', '0004_servicepayment_delete_bookingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
