# Generated by Django 5.0.2 on 2024-03-15 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace_forte_app', '0005_servicepayment_isexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='receiptId',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingpayment',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingpayment',
            name='receiptId',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
